# Generated by Django 5.2.4 on 2025-07-20 07:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("price_manager", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="commodityprices",
            name="date",
            field=models.DateField(
                default=datetime.datetime(2025, 7, 20, 15, 59, 54, 996079)
            ),
        ),
    ]
